name: Release

on:
  release:
    types:
      - published

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Ensure the code is checked out

      - name: Test
        run: echo ${{ github.ref_name }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # List files for debugging
      - name: List directory contents
        run: ls -R  # To confirm the presence of backend.dockerfile

      # Build and push backend Docker image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: luciansans/webcounter-backend:${{ github.ref_name }}
          context: .  
          file: ./backend.dockerfile
