name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend Docker image with release tag
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./backend.Dockerfile
          tags: luciansans/webcounter-backend:${{ github.event.release.tag_name }}

      # Build and push frontend Docker image with release tag
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./frontend.Dockerfile
          tags: luciansans/webcounter-frontend:${{ github.event.release.tag_name }}
