name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        uses: echo ${{ github.ref_name }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend&frontend Docker image
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./backend.dockerfile
          tags: luciansans/webcounter-backend:${{ github.ref_name }}

      
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./frontend.dockerfile
          tags: luciansans/webcounter-frontend:${{ github.ref_name }}