name: Assignment 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v4

      # Set up Python (if you need it for tests)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      # Install dependencies and run fake tests (if needed)
      - name: Install dependencies and run fake tests
        run: |
          echo "Installing dependencies..."
          pip install -r requirements.txt  # Replace this with your actual test command if needed
          echo "Running fake tests..."
          sleep 3  # Fake test step (replace this with real tests)

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend Docker image
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend  # Assuming backend Dockerfile is in the backend directory
          file: ./backend.dockerfile
          tags: username/webcounter-backend:${{ github.sha }}

      # Build and push frontend Docker image
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./frontend  # Assuming frontend Dockerfile is in the frontend directory
          file: ./frontend.dockerfile
          tags: username/webcounter-frontend:${{ github.sha }}