name : assignment 

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

  steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Ree files
      run: ls -lah
      